In [2]:
import numpy as np
from scipy import sparse
import matplotlib.pyplot as plt
import scipy.linalg as sla
%matplotlib inline

from arnoldi import arnoldi

In [3]:
A = sla.toeplitz([2, -1, 0, 0])
print(A)

[[ 2 -1  0  0]
 [-1  2 -1  0]
 [ 0 -1  2 -1]
 [ 0  0 -1  2]]


In [4]:
#r0 = np.ones((4,))
r0 = np.random.rand(4)
V, H = arnoldi(A, 3, v0=r0)

In [5]:
print(V)
print(H)

[[ 0.45373122  0.48435014  0.26417373]
 [ 0.40836106 -0.85448227  0.0156844 ]
 [ 0.6263504   0.07197178  0.45609241]
 [ 0.48482409  0.17345043 -0.84967403]]
[[  5.10533925e-01   5.52195993e-01   8.88178420e-16]
 [  5.52195993e-01   2.92576737e+00   5.88772201e-01]
 [  0.00000000e+00   5.88772201e-01   2.75246586e+00]]


In [6]:
print(np.sort(sla.eigvals(H).real))
print(np.sort(sla.eigvals(A).real))

[ 0.38328065  2.31061434  3.49487217]
[ 0.38196601  1.38196601  2.61803399  3.61803399]
